import {
  allPurposeYards,
  combinedPoints,
  completionPct,
  defensiveTouchdowns,
  fgPct,
  formatDecimal,
  formatPercent,
  formatWhole,
  gameScoringMargin,
  gamesPlayed,
  opponentPointsPerGame,
  patPct,
  playerPassingYardsPerGame,
  playerInterceptionsPerGame,
  playerPointsPerGame,
  playerReceivingYardsPerGame,
  playerReturnYardsPerGame,
  playerRushingYardsPerGame,
  playerSacksPerGame,
  playerTotalTacklesPerGame,
  playerTotalYardsPerGame,
  puntAverage,
  returnTouchdowns,
  scoringMarginPerGame,
  stat,
  teamPointsPerGame,
  teamWinPct,
  totalKickingPoints,
  totalOffenseYards,
  totalPoints,
  totalReturnYards,
  totalTouchdowns,
  totalYards,
  trackedGames,
  yardsPerCarry,
  yardsPerCatch,
  yardsPerCompletion,
} from "./footballRecordsData";

const whole = (value) => formatWhole(value);
const oneDecimal = (value) => formatDecimal(value, 1);
const twoDecimals = (value) => formatDecimal(value, 2);
const pct = (value) => formatPercent(value, 1);

export const TEAM_SINGLE_GAME_SECTIONS = [
  {
    title: "Team Success",
    records: [
      { key: "team-points", label: "Points Scored", abbr: "PTS", valueFn: (row) => stat(row, "TeamScore"), displayFn: whole },
      {
        key: "team-fewest-allowed",
        label: "Fewest Points Allowed",
        abbr: "OPP",
        sortDirection: "asc",
        includeZero: true,
        valueFn: (row) => stat(row, "OpponentScore"),
        displayFn: whole,
      },
      {
        key: "team-margin-victory",
        label: "Largest Margin of Victory",
        abbr: "MOV",
        valueFn: (row) => {
          const margin = gameScoringMargin(row);
          return Number.isFinite(margin) && margin > 0 ? margin : null;
        },
        displayFn: whole,
      },
      {
        key: "team-margin-defeat",
        label: "Largest Margin of Defeat",
        abbr: "MOD",
        valueFn: (row) => {
          const margin = gameScoringMargin(row);
          return Number.isFinite(margin) && margin < 0 ? Math.abs(margin) : null;
        },
        displayFn: whole,
      },
      { key: "team-combined-points", label: "Most Combined Points", abbr: "TOT", valueFn: combinedPoints, displayFn: whole },
      { key: "team-passing-yards", label: "Passing Yards", abbr: "PYD", valueFn: (row) => stat(row, "PassingYards"), displayFn: whole },
      { key: "team-rushing-yards", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      { key: "team-total-offense", label: "Total Offense Yards", abbr: "OFF", valueFn: totalOffenseYards, displayFn: whole },
    ],
  },
  {
    title: "Offense",
    records: [
      { key: "team-pass-comp", label: "Pass Completions", abbr: "COMP", valueFn: (row) => stat(row, "PassingComp"), displayFn: whole },
      { key: "team-pass-att", label: "Pass Attempts", abbr: "ATT", valueFn: (row) => stat(row, "PassingAtt"), displayFn: whole },
      {
        key: "team-pass-pct",
        label: "Completion Percentage",
        abbr: "COMP%",
        qualifierText: "Minimum of 10 attempts",
        qualifyFn: (row) => stat(row, "PassingAtt") >= 10,
        valueFn: completionPct,
        displayFn: pct,
      },
      { key: "team-pass-td", label: "Passing TD", abbr: "PTD", valueFn: (row) => stat(row, "PassingTD"), displayFn: whole },
      { key: "team-rush-att", label: "Rushing Attempts", abbr: "CAR", valueFn: (row) => stat(row, "RushingNum"), displayFn: whole },
      { key: "team-rush-yds", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      {
        key: "team-ypc",
        label: "Yards per Carry",
        abbr: "Y/C",
        qualifierText: "Minimum of 15 carries",
        qualifyFn: (row) => stat(row, "RushingNum") >= 15,
        valueFn: yardsPerCarry,
        displayFn: oneDecimal,
      },
      { key: "team-rush-td", label: "Rushing TD", abbr: "RTD", valueFn: (row) => stat(row, "RushingTDNum"), displayFn: whole },
      { key: "team-receptions", label: "Receptions", abbr: "REC", valueFn: (row) => stat(row, "ReceivingNum"), displayFn: whole },
      { key: "team-rec-yds", label: "Receiving Yards", abbr: "RECY", valueFn: (row) => stat(row, "ReceivingYards"), displayFn: whole },
      { key: "team-rec-td", label: "Receiving TD", abbr: "RECTD", valueFn: (row) => stat(row, "ReceivingTDNum"), displayFn: whole },
    ],
  },
  {
    title: "Defense",
    records: [
      { key: "team-solo-tackles", label: "Solo Tackles", abbr: "TCK", valueFn: (row) => stat(row, "Tackles"), displayFn: whole },
      { key: "team-assists", label: "Assists", abbr: "AST", valueFn: (row) => stat(row, "Assists"), displayFn: whole },
      { key: "team-total-tackles", label: "Total Tackles", abbr: "TTK", valueFn: (row) => stat(row, "TotalTackles"), displayFn: whole },
      { key: "team-tfl", label: "Tackles for Loss", abbr: "TFL", valueFn: (row) => stat(row, "TacklesForLoss"), displayFn: oneDecimal },
      { key: "team-sacks", label: "Sacks", abbr: "SK", valueFn: (row) => stat(row, "Sacks"), displayFn: oneDecimal },
      { key: "team-hurries", label: "QB Hurries", abbr: "QBH", valueFn: (row) => stat(row, "QBHurries"), displayFn: whole },
      { key: "team-ints", label: "Interceptions", abbr: "INT", valueFn: (row) => stat(row, "Ints"), displayFn: whole },
      { key: "team-int-yards", label: "INT Return Yards", abbr: "INTY", valueFn: (row) => stat(row, "IntYards"), displayFn: whole },
      { key: "team-pd", label: "Passes Defensed", abbr: "PD", valueFn: (row) => stat(row, "PassesDefensed"), displayFn: whole },
      { key: "team-cf", label: "Caused Fumbles", abbr: "CF", valueFn: (row) => stat(row, "CausedFumbles"), displayFn: whole },
      { key: "team-fr", label: "Fumble Recoveries", abbr: "FR", valueFn: (row) => stat(row, "FumbleRecoveries"), displayFn: whole },
    ],
  },
  {
    title: "Special Teams & Scoring",
    records: [
      { key: "team-return-yards", label: "Total Return Yards", abbr: "RET", valueFn: totalReturnYards, displayFn: whole },
      { key: "team-kor-yards", label: "Kickoff Return Yards", abbr: "KRY", valueFn: (row) => stat(row, "KickoffReturnYards"), displayFn: whole },
      { key: "team-pr-yards", label: "Punt Return Yards", abbr: "PRY", valueFn: (row) => stat(row, "PuntReturnYards"), displayFn: whole },
      { key: "team-return-tds", label: "Return TD", abbr: "RTD", valueFn: returnTouchdowns, displayFn: whole },
      { key: "team-punts", label: "Punts", abbr: "PNT", valueFn: (row) => stat(row, "PuntNum"), displayFn: whole },
      {
        key: "team-punt-average",
        label: "Punt Average",
        abbr: "AVG",
        qualifierText: "Minimum of 3 punts",
        qualifyFn: (row) => stat(row, "PuntNum") >= 3,
        valueFn: puntAverage,
        displayFn: twoDecimals,
      },
      { key: "team-punt-inside-20", label: "Punts Inside 20", abbr: "I20", valueFn: (row) => stat(row, "PuntInside20"), displayFn: whole },
      { key: "team-touchbacks", label: "Kickoff Touchbacks", abbr: "TB", valueFn: (row) => stat(row, "KickoffTouchbacks"), displayFn: whole },
      { key: "team-pat-made", label: "PAT Made", abbr: "PAT", valueFn: (row) => stat(row, "PatKickingMade"), displayFn: whole },
      { key: "team-fg-made", label: "Field Goals Made", abbr: "FG", valueFn: (row) => stat(row, "FGMade"), displayFn: whole },
      { key: "team-kicking-points", label: "Kicking Points", abbr: "KPTS", valueFn: totalKickingPoints, displayFn: whole },
      { key: "team-total-points", label: "Individual Points Scored", abbr: "PTS", valueFn: totalPoints, displayFn: whole },
      { key: "team-total-tds", label: "Total Touchdowns", abbr: "TD", valueFn: totalTouchdowns, displayFn: whole },
    ],
  },
];

export const TEAM_SEASON_SECTIONS = [
  {
    title: "Team Success",
    records: [
      { key: "season-games", label: "Games Played", abbr: "GP", valueFn: gamesPlayed, displayFn: whole },
      { key: "season-wins", label: "Wins", abbr: "W", valueFn: (row) => stat(row, "OverallWins"), displayFn: whole },
      {
        key: "season-win-pct",
        label: "Winning Percentage",
        abbr: "WIN%",
        qualifierText: "Minimum of 8 games",
        qualifyFn: (row) => gamesPlayed(row) >= 8,
        valueFn: teamWinPct,
        displayFn: pct,
      },
      { key: "season-points-for", label: "Points Scored", abbr: "PF", valueFn: (row) => stat(row, "PointsFor"), displayFn: whole },
      {
        key: "season-points-per-game",
        label: "Points per Game",
        abbr: "PPG",
        qualifierText: "Minimum of 8 games",
        qualifyFn: (row) => gamesPlayed(row) >= 8,
        valueFn: teamPointsPerGame,
        displayFn: oneDecimal,
      },
      {
        key: "season-opp-points-per-game",
        label: "Fewest Opponent Points per Game",
        abbr: "OPP/G",
        sortDirection: "asc",
        qualifierText: "Minimum of 8 games",
        qualifyFn: (row) => gamesPlayed(row) >= 8,
        valueFn: opponentPointsPerGame,
        displayFn: oneDecimal,
      },
      {
        key: "season-margin",
        label: "Best Average Scoring Margin",
        abbr: "MARGIN",
        qualifierText: "Minimum of 8 games",
        qualifyFn: (row) => gamesPlayed(row) >= 8,
        valueFn: scoringMarginPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-pass-yards", label: "Passing Yards", abbr: "PYD", valueFn: (row) => stat(row, "PassingYards"), displayFn: whole },
      { key: "season-rush-yards", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      { key: "season-total-offense", label: "Total Offense Yards", abbr: "OFF", valueFn: totalOffenseYards, displayFn: whole },
    ],
  },
  {
    title: "Offense",
    records: [
      { key: "season-pass-comp", label: "Pass Completions", abbr: "COMP", valueFn: (row) => stat(row, "PassingComp"), displayFn: whole },
      { key: "season-pass-att", label: "Pass Attempts", abbr: "ATT", valueFn: (row) => stat(row, "PassingAtt"), displayFn: whole },
      {
        key: "season-pass-pct",
        label: "Completion Percentage",
        abbr: "COMP%",
        qualifierText: "Minimum of 60 attempts",
        qualifyFn: (row) => stat(row, "PassingAtt") >= 60,
        valueFn: completionPct,
        displayFn: pct,
      },
      { key: "season-pass-td", label: "Passing TD", abbr: "PTD", valueFn: (row) => stat(row, "PassingTD"), displayFn: whole },
      { key: "season-rush-att", label: "Rushing Attempts", abbr: "CAR", valueFn: (row) => stat(row, "RushingNum"), displayFn: whole },
      { key: "season-rush-yds", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      {
        key: "season-ypc",
        label: "Yards per Carry",
        abbr: "Y/C",
        qualifierText: "Minimum of 100 carries",
        qualifyFn: (row) => stat(row, "RushingNum") >= 100,
        valueFn: yardsPerCarry,
        displayFn: oneDecimal,
      },
      { key: "season-rush-td", label: "Rushing TD", abbr: "RTD", valueFn: (row) => stat(row, "RushingTDNum"), displayFn: whole },
      { key: "season-rec", label: "Receptions", abbr: "REC", valueFn: (row) => stat(row, "ReceivingNum"), displayFn: whole },
      { key: "season-rec-yds", label: "Receiving Yards", abbr: "RECY", valueFn: (row) => stat(row, "ReceivingYards"), displayFn: whole },
      {
        key: "season-ypc-receiving",
        label: "Yards per Catch",
        abbr: "Y/R",
        qualifierText: "Minimum of 20 receptions",
        qualifyFn: (row) => stat(row, "ReceivingNum") >= 20,
        valueFn: yardsPerCatch,
        displayFn: oneDecimal,
      },
      { key: "season-rec-td", label: "Receiving TD", abbr: "RECTD", valueFn: (row) => stat(row, "ReceivingTDNum"), displayFn: whole },
    ],
  },
  {
    title: "Defense",
    records: [
      { key: "season-solo-tackles", label: "Solo Tackles", abbr: "TCK", valueFn: (row) => stat(row, "Tackles"), displayFn: whole },
      { key: "season-assists", label: "Assists", abbr: "AST", valueFn: (row) => stat(row, "Assists"), displayFn: whole },
      { key: "season-total-tackles", label: "Total Tackles", abbr: "TTK", valueFn: (row) => stat(row, "TotalTackles"), displayFn: whole },
      { key: "season-tfl", label: "Tackles for Loss", abbr: "TFL", valueFn: (row) => stat(row, "TacklesForLoss"), displayFn: oneDecimal },
      { key: "season-sacks", label: "Sacks", abbr: "SK", valueFn: (row) => stat(row, "Sacks"), displayFn: oneDecimal },
      { key: "season-hurries", label: "QB Hurries", abbr: "QBH", valueFn: (row) => stat(row, "QBHurries"), displayFn: whole },
      { key: "season-ints", label: "Interceptions", abbr: "INT", valueFn: (row) => stat(row, "Ints"), displayFn: whole },
      { key: "season-int-yards", label: "INT Return Yards", abbr: "INTY", valueFn: (row) => stat(row, "IntYards"), displayFn: whole },
      { key: "season-pd", label: "Passes Defensed", abbr: "PD", valueFn: (row) => stat(row, "PassesDefensed"), displayFn: whole },
      { key: "season-cf", label: "Caused Fumbles", abbr: "CF", valueFn: (row) => stat(row, "CausedFumbles"), displayFn: whole },
      { key: "season-fr", label: "Fumble Recoveries", abbr: "FR", valueFn: (row) => stat(row, "FumbleRecoveries"), displayFn: whole },
    ],
  },
  {
    title: "Special Teams & Scoring",
    records: [
      { key: "season-return-yards", label: "Total Return Yards", abbr: "RET", valueFn: totalReturnYards, displayFn: whole },
      { key: "season-kor-yards", label: "Kickoff Return Yards", abbr: "KRY", valueFn: (row) => stat(row, "KickoffReturnYards"), displayFn: whole },
      { key: "season-pr-yards", label: "Punt Return Yards", abbr: "PRY", valueFn: (row) => stat(row, "PuntReturnYards"), displayFn: whole },
      { key: "season-return-tds", label: "Return TD", abbr: "RTD", valueFn: returnTouchdowns, displayFn: whole },
      { key: "season-punts", label: "Punts", abbr: "PNT", valueFn: (row) => stat(row, "PuntNum"), displayFn: whole },
      {
        key: "season-punt-average",
        label: "Punt Average",
        abbr: "AVG",
        qualifierText: "Minimum of 12 punts",
        qualifyFn: (row) => stat(row, "PuntNum") >= 12,
        valueFn: puntAverage,
        displayFn: twoDecimals,
      },
      { key: "season-inside-20", label: "Punts Inside 20", abbr: "I20", valueFn: (row) => stat(row, "PuntInside20"), displayFn: whole },
      { key: "season-touchbacks", label: "Kickoff Touchbacks", abbr: "TB", valueFn: (row) => stat(row, "KickoffTouchbacks"), displayFn: whole },
      { key: "season-pat-made", label: "PAT Made", abbr: "PAT", valueFn: (row) => stat(row, "PatKickingMade"), displayFn: whole },
      {
        key: "season-pat-pct",
        label: "PAT Percentage",
        abbr: "PAT%",
        qualifierText: "Minimum of 10 attempts",
        qualifyFn: (row) => stat(row, "PatKickingAtt") >= 10,
        valueFn: patPct,
        displayFn: pct,
      },
      { key: "season-fg-made", label: "Field Goals Made", abbr: "FG", valueFn: (row) => stat(row, "FGMade"), displayFn: whole },
      {
        key: "season-fg-pct",
        label: "Field Goal Percentage",
        abbr: "FG%",
        qualifierText: "Minimum of 3 attempts",
        qualifyFn: (row) => stat(row, "FGAttempted") >= 3,
        valueFn: fgPct,
        displayFn: pct,
      },
      { key: "season-kicking-points", label: "Kicking Points", abbr: "KPTS", valueFn: totalKickingPoints, displayFn: whole },
      { key: "season-total-points", label: "Individual Points Scored", abbr: "PTS", valueFn: totalPoints, displayFn: whole },
      { key: "season-total-tds", label: "Total Touchdowns", abbr: "TD", valueFn: totalTouchdowns, displayFn: whole },
    ],
  },
];

export const INDIVIDUAL_SINGLE_GAME_SECTIONS = [
  {
    title: "Passing",
    records: [
      { key: "game-pass-comp", label: "Pass Completions", abbr: "COMP", valueFn: (row) => stat(row, "PassingComp"), displayFn: whole },
      { key: "game-pass-att", label: "Pass Attempts", abbr: "ATT", valueFn: (row) => stat(row, "PassingAtt"), displayFn: whole },
      {
        key: "game-pass-pct",
        label: "Completion Percentage",
        abbr: "COMP%",
        qualifierText: "Minimum of 10 attempts",
        qualifyFn: (row) => stat(row, "PassingAtt") >= 10,
        valueFn: completionPct,
        displayFn: pct,
      },
      { key: "game-pass-yards", label: "Passing Yards", abbr: "PYD", valueFn: (row) => stat(row, "PassingYards"), displayFn: whole },
      {
        key: "game-ypc-pass",
        label: "Yards per Completion",
        abbr: "Y/C",
        qualifierText: "Minimum of 5 completions",
        qualifyFn: (row) => stat(row, "PassingComp") >= 5,
        valueFn: yardsPerCompletion,
        displayFn: oneDecimal,
      },
      { key: "game-pass-td", label: "Passing TD", abbr: "PTD", valueFn: (row) => stat(row, "PassingTD"), displayFn: whole },
    ],
  },
  {
    title: "Rushing & Receiving",
    records: [
      { key: "game-rush-att", label: "Rushing Attempts", abbr: "CAR", valueFn: (row) => stat(row, "RushingNum"), displayFn: whole },
      { key: "game-rush-yards", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      {
        key: "game-ypc-rushing",
        label: "Yards per Carry",
        abbr: "Y/C",
        qualifierText: "Minimum of 10 carries",
        qualifyFn: (row) => stat(row, "RushingNum") >= 10,
        valueFn: yardsPerCarry,
        displayFn: oneDecimal,
      },
      { key: "game-rush-td", label: "Rushing TD", abbr: "RTD", valueFn: (row) => stat(row, "RushingTDNum"), displayFn: whole },
      { key: "game-receptions", label: "Receptions", abbr: "REC", valueFn: (row) => stat(row, "ReceivingNum"), displayFn: whole },
      { key: "game-rec-yards", label: "Receiving Yards", abbr: "RECY", valueFn: (row) => stat(row, "ReceivingYards"), displayFn: whole },
      {
        key: "game-ypc-receiving",
        label: "Yards per Catch",
        abbr: "Y/R",
        qualifierText: "Minimum of 4 receptions",
        qualifyFn: (row) => stat(row, "ReceivingNum") >= 4,
        valueFn: yardsPerCatch,
        displayFn: oneDecimal,
      },
      { key: "game-rec-td", label: "Receiving TD", abbr: "RECTD", valueFn: (row) => stat(row, "ReceivingTDNum"), displayFn: whole },
      { key: "game-all-purpose", label: "All-Purpose Yards", abbr: "APY", valueFn: allPurposeYards, displayFn: whole },
      { key: "game-total-yards", label: "Total Yards", abbr: "TYD", valueFn: totalYards, displayFn: whole },
    ],
  },
  {
    title: "Defense",
    records: [
      { key: "game-solo-tackles", label: "Solo Tackles", abbr: "TCK", valueFn: (row) => stat(row, "Tackles"), displayFn: whole },
      { key: "game-assists", label: "Assists", abbr: "AST", valueFn: (row) => stat(row, "Assists"), displayFn: whole },
      { key: "game-total-tackles", label: "Total Tackles", abbr: "TTK", valueFn: (row) => stat(row, "TotalTackles"), displayFn: whole },
      { key: "game-tfl", label: "Tackles for Loss", abbr: "TFL", valueFn: (row) => stat(row, "TacklesForLoss"), displayFn: oneDecimal },
      { key: "game-sacks", label: "Sacks", abbr: "SK", valueFn: (row) => stat(row, "Sacks"), displayFn: oneDecimal },
      { key: "game-hurries", label: "QB Hurries", abbr: "QBH", valueFn: (row) => stat(row, "QBHurries"), displayFn: whole },
      { key: "game-ints", label: "Interceptions", abbr: "INT", valueFn: (row) => stat(row, "Ints"), displayFn: whole },
      { key: "game-int-yards", label: "INT Return Yards", abbr: "INTY", valueFn: (row) => stat(row, "IntYards"), displayFn: whole },
      { key: "game-pd", label: "Passes Defensed", abbr: "PD", valueFn: (row) => stat(row, "PassesDefensed"), displayFn: whole },
      { key: "game-cf", label: "Caused Fumbles", abbr: "CF", valueFn: (row) => stat(row, "CausedFumbles"), displayFn: whole },
      { key: "game-fr", label: "Fumble Recoveries", abbr: "FR", valueFn: (row) => stat(row, "FumbleRecoveries"), displayFn: whole },
      { key: "game-def-td", label: "Defensive TD", abbr: "DTD", valueFn: defensiveTouchdowns, displayFn: whole },
    ],
  },
  {
    title: "Special Teams & Scoring",
    records: [
      { key: "game-return-yards", label: "Total Return Yards", abbr: "RET", valueFn: totalReturnYards, displayFn: whole },
      { key: "game-kor-yards", label: "Kickoff Return Yards", abbr: "KRY", valueFn: (row) => stat(row, "KickoffReturnYards"), displayFn: whole },
      { key: "game-pr-yards", label: "Punt Return Yards", abbr: "PRY", valueFn: (row) => stat(row, "PuntReturnYards"), displayFn: whole },
      { key: "game-return-tds", label: "Return TD", abbr: "RTD", valueFn: returnTouchdowns, displayFn: whole },
      { key: "game-punts", label: "Punts", abbr: "PNT", valueFn: (row) => stat(row, "PuntNum"), displayFn: whole },
      {
        key: "game-punt-average",
        label: "Punt Average",
        abbr: "AVG",
        qualifierText: "Minimum of 3 punts",
        qualifyFn: (row) => stat(row, "PuntNum") >= 3,
        valueFn: puntAverage,
        displayFn: twoDecimals,
      },
      { key: "game-inside-20", label: "Punts Inside 20", abbr: "I20", valueFn: (row) => stat(row, "PuntInside20"), displayFn: whole },
      { key: "game-touchbacks", label: "Kickoff Touchbacks", abbr: "TB", valueFn: (row) => stat(row, "KickoffTouchbacks"), displayFn: whole },
      { key: "game-pat-made", label: "PAT Made", abbr: "PAT", valueFn: (row) => stat(row, "PatKickingMade"), displayFn: whole },
      { key: "game-fg-made", label: "Field Goals Made", abbr: "FG", valueFn: (row) => stat(row, "FGMade"), displayFn: whole },
      { key: "game-kicking-points", label: "Kicking Points", abbr: "KPTS", valueFn: totalKickingPoints, displayFn: whole },
      { key: "game-total-points", label: "Points", abbr: "PTS", valueFn: totalPoints, displayFn: whole },
      { key: "game-total-td", label: "Total Touchdowns", abbr: "TD", valueFn: totalTouchdowns, displayFn: whole },
    ],
  },
];

export const INDIVIDUAL_SEASON_SECTIONS = [
  {
    title: "Passing",
    records: [
      { key: "season-player-games", label: "Tracked Games", abbr: "G", valueFn: trackedGames, displayFn: whole },
      { key: "season-player-pass-comp", label: "Pass Completions", abbr: "COMP", valueFn: (row) => stat(row, "PassingComp"), displayFn: whole },
      { key: "season-player-pass-att", label: "Pass Attempts", abbr: "ATT", valueFn: (row) => stat(row, "PassingAtt"), displayFn: whole },
      {
        key: "season-player-pass-pct",
        label: "Completion Percentage",
        abbr: "COMP%",
        qualifierText: "Minimum of 40 attempts",
        qualifyFn: (row) => stat(row, "PassingAtt") >= 40,
        valueFn: completionPct,
        displayFn: pct,
      },
      { key: "season-player-pass-yards", label: "Passing Yards", abbr: "PYD", valueFn: (row) => stat(row, "PassingYards"), displayFn: whole },
      {
        key: "season-player-pass-yards-per-game",
        label: "Passing Yards per Game",
        abbr: "PY/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerPassingYardsPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-player-pass-td", label: "Passing TD", abbr: "PTD", valueFn: (row) => stat(row, "PassingTD"), displayFn: whole },
    ],
  },
  {
    title: "Rushing & Receiving",
    records: [
      { key: "season-player-rush-att", label: "Rushing Attempts", abbr: "CAR", valueFn: (row) => stat(row, "RushingNum"), displayFn: whole },
      { key: "season-player-rush-yards", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      {
        key: "season-player-rush-yards-per-game",
        label: "Rushing Yards per Game",
        abbr: "RY/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerRushingYardsPerGame,
        displayFn: oneDecimal,
      },
      {
        key: "season-player-ypc",
        label: "Yards per Carry",
        abbr: "Y/C",
        qualifierText: "Minimum of 40 carries",
        qualifyFn: (row) => stat(row, "RushingNum") >= 40,
        valueFn: yardsPerCarry,
        displayFn: oneDecimal,
      },
      { key: "season-player-rush-td", label: "Rushing TD", abbr: "RTD", valueFn: (row) => stat(row, "RushingTDNum"), displayFn: whole },
      { key: "season-player-receptions", label: "Receptions", abbr: "REC", valueFn: (row) => stat(row, "ReceivingNum"), displayFn: whole },
      { key: "season-player-rec-yards", label: "Receiving Yards", abbr: "RECY", valueFn: (row) => stat(row, "ReceivingYards"), displayFn: whole },
      {
        key: "season-player-rec-yards-per-game",
        label: "Receiving Yards per Game",
        abbr: "RC/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerReceivingYardsPerGame,
        displayFn: oneDecimal,
      },
      {
        key: "season-player-yards-per-catch",
        label: "Yards per Catch",
        abbr: "Y/R",
        qualifierText: "Minimum of 15 receptions",
        qualifyFn: (row) => stat(row, "ReceivingNum") >= 15,
        valueFn: yardsPerCatch,
        displayFn: oneDecimal,
      },
      { key: "season-player-rec-td", label: "Receiving TD", abbr: "RECTD", valueFn: (row) => stat(row, "ReceivingTDNum"), displayFn: whole },
      { key: "season-player-all-purpose", label: "All-Purpose Yards", abbr: "APY", valueFn: allPurposeYards, displayFn: whole },
      { key: "season-player-total-yards", label: "Total Yards", abbr: "TYD", valueFn: totalYards, displayFn: whole },
      {
        key: "season-player-total-yards-per-game",
        label: "Total Yards per Game",
        abbr: "TY/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerTotalYardsPerGame,
        displayFn: oneDecimal,
      },
    ],
  },
  {
    title: "Defense",
    records: [
      { key: "season-player-solo-tackles", label: "Solo Tackles", abbr: "TCK", valueFn: (row) => stat(row, "Tackles"), displayFn: whole },
      { key: "season-player-assists", label: "Assists", abbr: "AST", valueFn: (row) => stat(row, "Assists"), displayFn: whole },
      { key: "season-player-total-tackles", label: "Total Tackles", abbr: "TTK", valueFn: (row) => stat(row, "TotalTackles"), displayFn: whole },
      {
        key: "season-player-total-tackles-per-game",
        label: "Total Tackles per Game",
        abbr: "TT/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerTotalTacklesPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-player-tfl", label: "Tackles for Loss", abbr: "TFL", valueFn: (row) => stat(row, "TacklesForLoss"), displayFn: oneDecimal },
      { key: "season-player-sacks", label: "Sacks", abbr: "SK", valueFn: (row) => stat(row, "Sacks"), displayFn: oneDecimal },
      {
        key: "season-player-sacks-per-game",
        label: "Sacks per Game",
        abbr: "SK/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerSacksPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-player-hurries", label: "QB Hurries", abbr: "QBH", valueFn: (row) => stat(row, "QBHurries"), displayFn: whole },
      { key: "season-player-ints", label: "Interceptions", abbr: "INT", valueFn: (row) => stat(row, "Ints"), displayFn: whole },
      {
        key: "season-player-ints-per-game",
        label: "Interceptions per Game",
        abbr: "INT/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerInterceptionsPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-player-int-yards", label: "INT Return Yards", abbr: "INTY", valueFn: (row) => stat(row, "IntYards"), displayFn: whole },
      { key: "season-player-pd", label: "Passes Defensed", abbr: "PD", valueFn: (row) => stat(row, "PassesDefensed"), displayFn: whole },
      { key: "season-player-cf", label: "Caused Fumbles", abbr: "CF", valueFn: (row) => stat(row, "CausedFumbles"), displayFn: whole },
      { key: "season-player-fr", label: "Fumble Recoveries", abbr: "FR", valueFn: (row) => stat(row, "FumbleRecoveries"), displayFn: whole },
      { key: "season-player-def-td", label: "Defensive TD", abbr: "DTD", valueFn: defensiveTouchdowns, displayFn: whole },
    ],
  },
  {
    title: "Special Teams & Scoring",
    records: [
      { key: "season-player-return-yards", label: "Total Return Yards", abbr: "RET", valueFn: totalReturnYards, displayFn: whole },
      {
        key: "season-player-return-yards-per-game",
        label: "Return Yards per Game",
        abbr: "RET/G",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerReturnYardsPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-player-kor-yards", label: "Kickoff Return Yards", abbr: "KRY", valueFn: (row) => stat(row, "KickoffReturnYards"), displayFn: whole },
      { key: "season-player-pr-yards", label: "Punt Return Yards", abbr: "PRY", valueFn: (row) => stat(row, "PuntReturnYards"), displayFn: whole },
      { key: "season-player-return-tds", label: "Return TD", abbr: "RTD", valueFn: returnTouchdowns, displayFn: whole },
      { key: "season-player-punts", label: "Punts", abbr: "PNT", valueFn: (row) => stat(row, "PuntNum"), displayFn: whole },
      {
        key: "season-player-punt-average",
        label: "Punt Average",
        abbr: "AVG",
        qualifierText: "Minimum of 8 punts",
        qualifyFn: (row) => stat(row, "PuntNum") >= 8,
        valueFn: puntAverage,
        displayFn: twoDecimals,
      },
      { key: "season-player-inside-20", label: "Punts Inside 20", abbr: "I20", valueFn: (row) => stat(row, "PuntInside20"), displayFn: whole },
      { key: "season-player-touchbacks", label: "Kickoff Touchbacks", abbr: "TB", valueFn: (row) => stat(row, "KickoffTouchbacks"), displayFn: whole },
      { key: "season-player-pat-made", label: "PAT Made", abbr: "PAT", valueFn: (row) => stat(row, "PatKickingMade"), displayFn: whole },
      { key: "season-player-fg-made", label: "Field Goals Made", abbr: "FG", valueFn: (row) => stat(row, "FGMade"), displayFn: whole },
      { key: "season-player-kicking-points", label: "Kicking Points", abbr: "KPTS", valueFn: totalKickingPoints, displayFn: whole },
      { key: "season-player-points", label: "Points", abbr: "PTS", valueFn: totalPoints, displayFn: whole },
      {
        key: "season-player-points-per-game",
        label: "Points per Game",
        abbr: "PPG",
        qualifierText: "Minimum of 6 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 6,
        valueFn: playerPointsPerGame,
        displayFn: oneDecimal,
      },
      { key: "season-player-total-td", label: "Total Touchdowns", abbr: "TD", valueFn: totalTouchdowns, displayFn: whole },
    ],
  },
  {
    title: "Milestones",
    records: [
      { key: "season-player-200-pass", label: "200-Yard Passing Games", abbr: "200P", valueFn: (row) => stat(row, "Passing200Games"), displayFn: whole },
      { key: "season-player-100-rush", label: "100-Yard Rushing Games", abbr: "100R", valueFn: (row) => stat(row, "Rushing100Games"), displayFn: whole },
      { key: "season-player-100-rec", label: "100-Yard Receiving Games", abbr: "100C", valueFn: (row) => stat(row, "Receiving100Games"), displayFn: whole },
      { key: "season-player-2-int", label: "2-Interception Games", abbr: "2INT", valueFn: (row) => stat(row, "TwoInterceptionGames"), displayFn: whole },
      { key: "season-player-10-tackle", label: "10-Tackle Games", abbr: "10TK", valueFn: (row) => stat(row, "TenTackleGames"), displayFn: whole },
      { key: "season-player-2-sack", label: "2-Sack Games", abbr: "2SK", valueFn: (row) => stat(row, "TwoSackGames"), displayFn: whole },
    ],
  },
];

export const INDIVIDUAL_CAREER_SECTIONS = [
  {
    title: "Passing",
    records: [
      { key: "career-player-games", label: "Tracked Games", abbr: "G", valueFn: trackedGames, displayFn: whole },
      { key: "career-player-pass-comp", label: "Pass Completions", abbr: "COMP", valueFn: (row) => stat(row, "PassingComp"), displayFn: whole },
      { key: "career-player-pass-att", label: "Pass Attempts", abbr: "ATT", valueFn: (row) => stat(row, "PassingAtt"), displayFn: whole },
      {
        key: "career-player-pass-pct",
        label: "Completion Percentage",
        abbr: "COMP%",
        qualifierText: "Minimum of 80 attempts",
        qualifyFn: (row) => stat(row, "PassingAtt") >= 80,
        valueFn: completionPct,
        displayFn: pct,
      },
      { key: "career-player-pass-yards", label: "Passing Yards", abbr: "PYD", valueFn: (row) => stat(row, "PassingYards"), displayFn: whole },
      { key: "career-player-pass-td", label: "Passing TD", abbr: "PTD", valueFn: (row) => stat(row, "PassingTD"), displayFn: whole },
    ],
  },
  {
    title: "Rushing & Receiving",
    records: [
      { key: "career-player-rush-att", label: "Rushing Attempts", abbr: "CAR", valueFn: (row) => stat(row, "RushingNum"), displayFn: whole },
      { key: "career-player-rush-yards", label: "Rushing Yards", abbr: "RYD", valueFn: (row) => stat(row, "RushingYards"), displayFn: whole },
      {
        key: "career-player-ypc",
        label: "Yards per Carry",
        abbr: "Y/C",
        qualifierText: "Minimum of 80 carries",
        qualifyFn: (row) => stat(row, "RushingNum") >= 80,
        valueFn: yardsPerCarry,
        displayFn: oneDecimal,
      },
      { key: "career-player-rush-td", label: "Rushing TD", abbr: "RTD", valueFn: (row) => stat(row, "RushingTDNum"), displayFn: whole },
      { key: "career-player-receptions", label: "Receptions", abbr: "REC", valueFn: (row) => stat(row, "ReceivingNum"), displayFn: whole },
      { key: "career-player-rec-yards", label: "Receiving Yards", abbr: "RECY", valueFn: (row) => stat(row, "ReceivingYards"), displayFn: whole },
      {
        key: "career-player-yards-per-catch",
        label: "Yards per Catch",
        abbr: "Y/R",
        qualifierText: "Minimum of 25 receptions",
        qualifyFn: (row) => stat(row, "ReceivingNum") >= 25,
        valueFn: yardsPerCatch,
        displayFn: oneDecimal,
      },
      { key: "career-player-rec-td", label: "Receiving TD", abbr: "RECTD", valueFn: (row) => stat(row, "ReceivingTDNum"), displayFn: whole },
      { key: "career-player-all-purpose", label: "All-Purpose Yards", abbr: "APY", valueFn: allPurposeYards, displayFn: whole },
      { key: "career-player-total-yards", label: "Total Yards", abbr: "TYD", valueFn: totalYards, displayFn: whole },
      {
        key: "career-player-total-yards-per-game",
        label: "Total Yards per Game",
        abbr: "TY/G",
        qualifierText: "Minimum of 12 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 12,
        valueFn: playerTotalYardsPerGame,
        displayFn: oneDecimal,
      },
    ],
  },
  {
    title: "Defense",
    records: [
      { key: "career-player-solo-tackles", label: "Solo Tackles", abbr: "TCK", valueFn: (row) => stat(row, "Tackles"), displayFn: whole },
      { key: "career-player-assists", label: "Assists", abbr: "AST", valueFn: (row) => stat(row, "Assists"), displayFn: whole },
      { key: "career-player-total-tackles", label: "Total Tackles", abbr: "TTK", valueFn: (row) => stat(row, "TotalTackles"), displayFn: whole },
      {
        key: "career-player-total-tackles-per-game",
        label: "Total Tackles per Game",
        abbr: "TT/G",
        qualifierText: "Minimum of 12 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 12,
        valueFn: playerTotalTacklesPerGame,
        displayFn: oneDecimal,
      },
      { key: "career-player-tfl", label: "Tackles for Loss", abbr: "TFL", valueFn: (row) => stat(row, "TacklesForLoss"), displayFn: oneDecimal },
      { key: "career-player-sacks", label: "Sacks", abbr: "SK", valueFn: (row) => stat(row, "Sacks"), displayFn: oneDecimal },
      {
        key: "career-player-sacks-per-game",
        label: "Sacks per Game",
        abbr: "SK/G",
        qualifierText: "Minimum of 12 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 12,
        valueFn: playerSacksPerGame,
        displayFn: oneDecimal,
      },
      { key: "career-player-hurries", label: "QB Hurries", abbr: "QBH", valueFn: (row) => stat(row, "QBHurries"), displayFn: whole },
      { key: "career-player-ints", label: "Interceptions", abbr: "INT", valueFn: (row) => stat(row, "Ints"), displayFn: whole },
      {
        key: "career-player-ints-per-game",
        label: "Interceptions per Game",
        abbr: "INT/G",
        qualifierText: "Minimum of 12 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 12,
        valueFn: playerInterceptionsPerGame,
        displayFn: oneDecimal,
      },
      { key: "career-player-int-yards", label: "INT Return Yards", abbr: "INTY", valueFn: (row) => stat(row, "IntYards"), displayFn: whole },
      { key: "career-player-pd", label: "Passes Defensed", abbr: "PD", valueFn: (row) => stat(row, "PassesDefensed"), displayFn: whole },
      { key: "career-player-cf", label: "Caused Fumbles", abbr: "CF", valueFn: (row) => stat(row, "CausedFumbles"), displayFn: whole },
      { key: "career-player-fr", label: "Fumble Recoveries", abbr: "FR", valueFn: (row) => stat(row, "FumbleRecoveries"), displayFn: whole },
      { key: "career-player-def-td", label: "Defensive TD", abbr: "DTD", valueFn: defensiveTouchdowns, displayFn: whole },
    ],
  },
  {
    title: "Special Teams & Scoring",
    records: [
      { key: "career-player-return-yards", label: "Total Return Yards", abbr: "RET", valueFn: totalReturnYards, displayFn: whole },
      {
        key: "career-player-return-yards-per-game",
        label: "Return Yards per Game",
        abbr: "RET/G",
        qualifierText: "Minimum of 12 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 12,
        valueFn: playerReturnYardsPerGame,
        displayFn: oneDecimal,
      },
      { key: "career-player-kor-yards", label: "Kickoff Return Yards", abbr: "KRY", valueFn: (row) => stat(row, "KickoffReturnYards"), displayFn: whole },
      { key: "career-player-pr-yards", label: "Punt Return Yards", abbr: "PRY", valueFn: (row) => stat(row, "PuntReturnYards"), displayFn: whole },
      { key: "career-player-return-tds", label: "Return TD", abbr: "RTD", valueFn: returnTouchdowns, displayFn: whole },
      { key: "career-player-punts", label: "Punts", abbr: "PNT", valueFn: (row) => stat(row, "PuntNum"), displayFn: whole },
      {
        key: "career-player-punt-average",
        label: "Punt Average",
        abbr: "AVG",
        qualifierText: "Minimum of 15 punts",
        qualifyFn: (row) => stat(row, "PuntNum") >= 15,
        valueFn: puntAverage,
        displayFn: twoDecimals,
      },
      { key: "career-player-inside-20", label: "Punts Inside 20", abbr: "I20", valueFn: (row) => stat(row, "PuntInside20"), displayFn: whole },
      { key: "career-player-touchbacks", label: "Kickoff Touchbacks", abbr: "TB", valueFn: (row) => stat(row, "KickoffTouchbacks"), displayFn: whole },
      { key: "career-player-pat-made", label: "PAT Made", abbr: "PAT", valueFn: (row) => stat(row, "PatKickingMade"), displayFn: whole },
      { key: "career-player-fg-made", label: "Field Goals Made", abbr: "FG", valueFn: (row) => stat(row, "FGMade"), displayFn: whole },
      { key: "career-player-kicking-points", label: "Kicking Points", abbr: "KPTS", valueFn: totalKickingPoints, displayFn: whole },
      { key: "career-player-points", label: "Points", abbr: "PTS", valueFn: totalPoints, displayFn: whole },
      {
        key: "career-player-points-per-game",
        label: "Points per Game",
        abbr: "PPG",
        qualifierText: "Minimum of 12 tracked games",
        qualifyFn: (row) => trackedGames(row) >= 12,
        valueFn: playerPointsPerGame,
        displayFn: oneDecimal,
      },
      { key: "career-player-total-td", label: "Total Touchdowns", abbr: "TD", valueFn: totalTouchdowns, displayFn: whole },
    ],
  },
  {
    title: "Milestones",
    records: [
      { key: "career-player-seasons", label: "Tracked Seasons", abbr: "S", valueFn: (row) => stat(row, "SeasonsTracked"), displayFn: whole },
      { key: "career-player-200-pass", label: "200-Yard Passing Games", abbr: "200P", valueFn: (row) => stat(row, "Passing200Games"), displayFn: whole },
      { key: "career-player-100-rush", label: "100-Yard Rushing Games", abbr: "100R", valueFn: (row) => stat(row, "Rushing100Games"), displayFn: whole },
      { key: "career-player-100-rec", label: "100-Yard Receiving Games", abbr: "100C", valueFn: (row) => stat(row, "Receiving100Games"), displayFn: whole },
      { key: "career-player-2-int", label: "2-Interception Games", abbr: "2INT", valueFn: (row) => stat(row, "TwoInterceptionGames"), displayFn: whole },
      { key: "career-player-10-tackle", label: "10-Tackle Games", abbr: "10TK", valueFn: (row) => stat(row, "TenTackleGames"), displayFn: whole },
      { key: "career-player-2-sack", label: "2-Sack Games", abbr: "2SK", valueFn: (row) => stat(row, "TwoSackGames"), displayFn: whole },
    ],
  },
];

export const FULL_CAREER_VIEW_CONFIG = {
  offense: {
    label: "Offense",
    defaultSort: "TotalYards",
    columns: [
      { key: "GamesTracked", label: "G", sortValue: trackedGames, render: (row) => whole(trackedGames(row)) },
      { key: "PassingComp", label: "Comp", sortValue: (row) => stat(row, "PassingComp"), render: (row) => whole(stat(row, "PassingComp")) },
      { key: "PassingAtt", label: "Att", sortValue: (row) => stat(row, "PassingAtt"), render: (row) => whole(stat(row, "PassingAtt")) },
      { key: "CompletionPct", label: "Comp%", sortValue: completionPct, render: (row) => pct(completionPct(row)) },
      { key: "PassingYards", label: "Pass Yds", sortValue: (row) => stat(row, "PassingYards"), render: (row) => whole(stat(row, "PassingYards")) },
      { key: "PassingTD", label: "Pass TD", sortValue: (row) => stat(row, "PassingTD"), render: (row) => whole(stat(row, "PassingTD")) },
      { key: "RushingNum", label: "Car", sortValue: (row) => stat(row, "RushingNum"), render: (row) => whole(stat(row, "RushingNum")) },
      { key: "RushingYards", label: "Rush Yds", sortValue: (row) => stat(row, "RushingYards"), render: (row) => whole(stat(row, "RushingYards")) },
      { key: "RushingTDNum", label: "Rush TD", sortValue: (row) => stat(row, "RushingTDNum"), render: (row) => whole(stat(row, "RushingTDNum")) },
      { key: "ReceivingNum", label: "Rec", sortValue: (row) => stat(row, "ReceivingNum"), render: (row) => whole(stat(row, "ReceivingNum")) },
      { key: "ReceivingYards", label: "Rec Yds", sortValue: (row) => stat(row, "ReceivingYards"), render: (row) => whole(stat(row, "ReceivingYards")) },
      { key: "ReceivingTDNum", label: "Rec TD", sortValue: (row) => stat(row, "ReceivingTDNum"), render: (row) => whole(stat(row, "ReceivingTDNum")) },
      { key: "AllPurposeYards", label: "APY", sortValue: allPurposeYards, render: (row) => whole(allPurposeYards(row)) },
      { key: "TotalYards", label: "Tot Yds", sortValue: totalYards, render: (row) => whole(totalYards(row)) },
    ],
  },
  defense: {
    label: "Defense",
    defaultSort: "TotalTackles",
    columns: [
      { key: "GamesTracked", label: "G", sortValue: trackedGames, render: (row) => whole(trackedGames(row)) },
      { key: "Tackles", label: "Tck", sortValue: (row) => stat(row, "Tackles"), render: (row) => whole(stat(row, "Tackles")) },
      { key: "Assists", label: "Ast", sortValue: (row) => stat(row, "Assists"), render: (row) => whole(stat(row, "Assists")) },
      { key: "TotalTackles", label: "Tot Tck", sortValue: (row) => stat(row, "TotalTackles"), render: (row) => whole(stat(row, "TotalTackles")) },
      { key: "TacklesForLoss", label: "TFL", sortValue: (row) => stat(row, "TacklesForLoss"), render: (row) => oneDecimal(stat(row, "TacklesForLoss")) },
      { key: "Sacks", label: "Sacks", sortValue: (row) => stat(row, "Sacks"), render: (row) => oneDecimal(stat(row, "Sacks")) },
      { key: "QBHurries", label: "QBH", sortValue: (row) => stat(row, "QBHurries"), render: (row) => whole(stat(row, "QBHurries")) },
      { key: "Ints", label: "Int", sortValue: (row) => stat(row, "Ints"), render: (row) => whole(stat(row, "Ints")) },
      { key: "IntYards", label: "Int Yds", sortValue: (row) => stat(row, "IntYards"), render: (row) => whole(stat(row, "IntYards")) },
      { key: "PassesDefensed", label: "PD", sortValue: (row) => stat(row, "PassesDefensed"), render: (row) => whole(stat(row, "PassesDefensed")) },
      { key: "CausedFumbles", label: "CF", sortValue: (row) => stat(row, "CausedFumbles"), render: (row) => whole(stat(row, "CausedFumbles")) },
      { key: "FumbleRecoveries", label: "FR", sortValue: (row) => stat(row, "FumbleRecoveries"), render: (row) => whole(stat(row, "FumbleRecoveries")) },
      { key: "DefensiveTD", label: "Def TD", sortValue: defensiveTouchdowns, render: (row) => whole(defensiveTouchdowns(row)) },
    ],
  },
  specialTeams: {
    label: "Special Teams",
    defaultSort: "TotalReturnYards",
    columns: [
      { key: "GamesTracked", label: "G", sortValue: trackedGames, render: (row) => whole(trackedGames(row)) },
      { key: "KickoffReturnYards", label: "KO Ret Yds", sortValue: (row) => stat(row, "KickoffReturnYards"), render: (row) => whole(stat(row, "KickoffReturnYards")) },
      { key: "PuntReturnYards", label: "PR Ret Yds", sortValue: (row) => stat(row, "PuntReturnYards"), render: (row) => whole(stat(row, "PuntReturnYards")) },
      { key: "TotalReturnYards", label: "Tot Ret", sortValue: totalReturnYards, render: (row) => whole(totalReturnYards(row)) },
      { key: "ReturnTD", label: "Ret TD", sortValue: returnTouchdowns, render: (row) => whole(returnTouchdowns(row)) },
      { key: "PuntNum", label: "Punts", sortValue: (row) => stat(row, "PuntNum"), render: (row) => whole(stat(row, "PuntNum")) },
      { key: "PuntAverage", label: "Punt Avg", sortValue: puntAverage, render: (row) => twoDecimals(puntAverage(row)) },
      { key: "PuntInside20", label: "I20", sortValue: (row) => stat(row, "PuntInside20"), render: (row) => whole(stat(row, "PuntInside20")) },
      { key: "KickoffTouchbacks", label: "TB", sortValue: (row) => stat(row, "KickoffTouchbacks"), render: (row) => whole(stat(row, "KickoffTouchbacks")) },
      { key: "PatKickingMade", label: "PAT", sortValue: (row) => stat(row, "PatKickingMade"), render: (row) => whole(stat(row, "PatKickingMade")) },
      { key: "FGMade", label: "FG", sortValue: (row) => stat(row, "FGMade"), render: (row) => whole(stat(row, "FGMade")) },
      { key: "TotalKickingPoints", label: "K Pts", sortValue: totalKickingPoints, render: (row) => whole(totalKickingPoints(row)) },
    ],
  },
  scoring: {
    label: "Scoring",
    defaultSort: "TotalPoints",
    columns: [
      { key: "GamesTracked", label: "G", sortValue: trackedGames, render: (row) => whole(trackedGames(row)) },
      { key: "TotalPoints", label: "Pts", sortValue: totalPoints, render: (row) => whole(totalPoints(row)) },
      { key: "PointsPerGame", label: "PPG", sortValue: playerPointsPerGame, render: (row) => oneDecimal(playerPointsPerGame(row)) },
      { key: "TotalTD", label: "TD", sortValue: totalTouchdowns, render: (row) => whole(totalTouchdowns(row)) },
      { key: "TotalKickingPoints", label: "Kick Pts", sortValue: totalKickingPoints, render: (row) => whole(totalKickingPoints(row)) },
      { key: "PatKickingMade", label: "PAT", sortValue: (row) => stat(row, "PatKickingMade"), render: (row) => whole(stat(row, "PatKickingMade")) },
      { key: "PatPct", label: "PAT%", sortValue: patPct, render: (row) => pct(patPct(row)) },
      { key: "FGMade", label: "FG", sortValue: (row) => stat(row, "FGMade"), render: (row) => whole(stat(row, "FGMade")) },
      { key: "FGPct", label: "FG%", sortValue: fgPct, render: (row) => pct(fgPct(row)) },
      { key: "ReturnTD", label: "Ret TD", sortValue: returnTouchdowns, render: (row) => whole(returnTouchdowns(row)) },
      { key: "DefensiveTD", label: "Def TD", sortValue: defensiveTouchdowns, render: (row) => whole(defensiveTouchdowns(row)) },
    ],
  },
  milestones: {
    label: "Milestones",
    defaultSort: "Passing200Games",
    columns: [
      { key: "GamesTracked", label: "G", sortValue: trackedGames, render: (row) => whole(trackedGames(row)) },
      { key: "SeasonsTracked", label: "S", sortValue: (row) => stat(row, "SeasonsTracked"), render: (row) => whole(stat(row, "SeasonsTracked")) },
      { key: "Passing200Games", label: "200P", sortValue: (row) => stat(row, "Passing200Games"), render: (row) => whole(stat(row, "Passing200Games")) },
      { key: "Rushing100Games", label: "100R", sortValue: (row) => stat(row, "Rushing100Games"), render: (row) => whole(stat(row, "Rushing100Games")) },
      { key: "Receiving100Games", label: "100C", sortValue: (row) => stat(row, "Receiving100Games"), render: (row) => whole(stat(row, "Receiving100Games")) },
      { key: "TwoInterceptionGames", label: "2INT", sortValue: (row) => stat(row, "TwoInterceptionGames"), render: (row) => whole(stat(row, "TwoInterceptionGames")) },
      { key: "TenTackleGames", label: "10TK", sortValue: (row) => stat(row, "TenTackleGames"), render: (row) => whole(stat(row, "TenTackleGames")) },
      { key: "TwoSackGames", label: "2SK", sortValue: (row) => stat(row, "TwoSackGames"), render: (row) => whole(stat(row, "TwoSackGames")) },
    ],
  },
};
