export const statsSearchItems = [
  {
    label: "Athletics Home",
    description: "St. Andrew's athletics stats home",
    to: "/athletics",
    featured: true,
    keywords: ["home", "athletics", "stats", "sports"],
  },
  {
    label: "Boys Basketball",
    description: "Program home",
    to: "/athletics/boys/basketball",
    featured: true,
    keywords: ["boys", "basketball", "home", "program"],
  },
  {
    label: "Full Year-by-Year Results",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/yearly-results",
    keywords: ["boys", "basketball", "results", "yearly", "history"],
  },
  {
    label: "Opponent Game History",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/records/opponents",
    keywords: ["boys", "basketball", "opponents", "results", "games"],
  },
  {
    label: "Full Team Stats",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/team/full",
    keywords: ["boys", "basketball", "team", "stats"],
  },
  {
    label: "Team Single Game Records",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/records/team",
    keywords: ["boys", "basketball", "team", "records", "single game"],
  },
  {
    label: "Team Season Records",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/team/season-records",
    keywords: ["boys", "basketball", "team", "season", "records"],
  },
  {
    label: "Full Career Stats",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/records/career",
    keywords: ["boys", "basketball", "career", "stats"],
  },
  {
    label: "Single Game Records",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/records/single-game",
    keywords: ["boys", "basketball", "single game", "records"],
  },
  {
    label: "Season Records",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/records/season",
    keywords: ["boys", "basketball", "season", "records"],
  },
  {
    label: "Career Records",
    description: "Boys Basketball",
    to: "/athletics/boys/basketball/records/career-records",
    keywords: ["boys", "basketball", "career", "records"],
  },
  {
    label: "Baseball",
    description: "Program home",
    to: "/athletics/boys/baseball",
    featured: true,
    keywords: ["boys", "baseball", "home", "program"],
  },
  {
    label: "Full Year-by-Year Results",
    description: "Baseball",
    to: "/athletics/boys/baseball/yearly-results",
    keywords: ["boys", "baseball", "results", "yearly", "history"],
  },
  {
    label: "Opponent Game History",
    description: "Baseball",
    to: "/athletics/boys/baseball/records/opponents",
    keywords: ["boys", "baseball", "opponents", "results", "games"],
  },
  {
    label: "Full Team Stats",
    description: "Baseball",
    to: "/athletics/boys/baseball/team/full",
    keywords: ["boys", "baseball", "team", "stats"],
  },
  {
    label: "Team Single Game Records",
    description: "Baseball",
    to: "/athletics/boys/baseball/records/team",
    keywords: ["boys", "baseball", "team", "records", "single game"],
  },
  {
    label: "Team Season Records",
    description: "Baseball",
    to: "/athletics/boys/baseball/team/season-records",
    keywords: ["boys", "baseball", "team", "season", "records"],
  },
  {
    label: "Full Career Stats",
    description: "Baseball",
    to: "/athletics/boys/baseball/records/career",
    keywords: ["boys", "baseball", "career", "stats"],
  },
  {
    label: "Single Game Records",
    description: "Baseball",
    to: "/athletics/boys/baseball/records/single-game",
    keywords: ["boys", "baseball", "single game", "records"],
  },
  {
    label: "Season Records",
    description: "Baseball",
    to: "/athletics/boys/baseball/records/season",
    keywords: ["boys", "baseball", "season", "records"],
  },
  {
    label: "Career Records",
    description: "Baseball",
    to: "/athletics/boys/baseball/records/career-records",
    keywords: ["boys", "baseball", "career", "records"],
  },
  {
    label: "Girls Basketball",
    description: "Program home",
    to: "/athletics/girls/basketball",
    featured: true,
    keywords: ["girls", "basketball", "home", "program"],
  },
  {
    label: "Full Year-by-Year Results",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/yearly-results",
    keywords: ["girls", "basketball", "results", "yearly", "history"],
  },
  {
    label: "Opponent Game History",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/records/opponents",
    keywords: ["girls", "basketball", "opponents", "results", "games"],
  },
  {
    label: "Full Team Stats",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/team/full",
    keywords: ["girls", "basketball", "team", "stats"],
  },
  {
    label: "Team Single Game Records",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/records/team",
    keywords: ["girls", "basketball", "team", "records", "single game"],
  },
  {
    label: "Team Season Records",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/team/season-records",
    keywords: ["girls", "basketball", "team", "season", "records"],
  },
  {
    label: "Full Career Stats",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/records/career",
    keywords: ["girls", "basketball", "career", "stats"],
  },
  {
    label: "Single Game Records",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/records/single-game",
    keywords: ["girls", "basketball", "single game", "records"],
  },
  {
    label: "Season Records",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/records/season",
    keywords: ["girls", "basketball", "season", "records"],
  },
  {
    label: "Career Records",
    description: "Girls Basketball",
    to: "/athletics/girls/basketball/records/career-records",
    keywords: ["girls", "basketball", "career", "records"],
  },
  {
    label: "Track & Field",
    description: "Program home",
    to: "/athletics/track/records/school",
    featured: true,
    keywords: ["track", "field", "menu", "home", "program"],
  },
  {
    label: "List of Champions",
    description: "Track & Field",
    to: "/athletics/track/champions",
    keywords: ["track", "field", "champions", "championships"],
  },
  {
    label: "School Records",
    description: "Track & Field",
    to: "/athletics/track/records/school",
    keywords: ["track", "field", "school", "records"],
  },
  {
    label: "Season Results",
    description: "Track & Field",
    to: "/athletics/track/yearly-results",
    keywords: ["track", "field", "season", "results"],
  },
  {
    label: "Swimming",
    description: "Program home",
    to: "/athletics/swimming/records/school",
    featured: true,
    keywords: ["swimming", "swim", "home", "program"],
  },
  {
    label: "State Champions",
    description: "Swimming",
    to: "/athletics/swimming/champions",
    keywords: ["swimming", "swim", "champions", "championships", "banners"],
  },
  {
    label: "School Records",
    description: "Swimming",
    to: "/athletics/swimming/records/school",
    keywords: ["swimming", "swim", "school", "records"],
  },
  {
    label: "Season Results",
    description: "Swimming",
    to: "/athletics/swimming/yearly-results",
    keywords: ["swimming", "swim", "season", "results"],
  },
  {
    label: "Tennis",
    description: "Program home",
    to: "/athletics/tennis",
    featured: true,
    keywords: ["tennis", "home", "overview", "program"],
  },
  {
    label: "Golf",
    description: "Program home",
    to: "/athletics/golf",
    featured: true,
    keywords: ["golf", "home", "overview", "program", "archive"],
  },
  {
    label: "Season Results",
    description: "Golf",
    to: "/athletics/golf/yearly-results",
    keywords: ["golf", "season", "results", "state", "archive"],
  },
];
